// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/renaldyhidayatt/redditgoent/ent/user"
	"github.com/renaldyhidayatt/redditgoent/ent/verificationtoken"
)

// VerificationTokenCreate is the builder for creating a VerificationToken entity.
type VerificationTokenCreate struct {
	config
	mutation *VerificationTokenMutation
	hooks    []Hook
}

// SetToken sets the "token" field.
func (vtc *VerificationTokenCreate) SetToken(s string) *VerificationTokenCreate {
	vtc.mutation.SetToken(s)
	return vtc
}

// SetCreatedAt sets the "created_at" field.
func (vtc *VerificationTokenCreate) SetCreatedAt(t time.Time) *VerificationTokenCreate {
	vtc.mutation.SetCreatedAt(t)
	return vtc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (vtc *VerificationTokenCreate) SetNillableCreatedAt(t *time.Time) *VerificationTokenCreate {
	if t != nil {
		vtc.SetCreatedAt(*t)
	}
	return vtc
}

// SetUpdatedAt sets the "updated_at" field.
func (vtc *VerificationTokenCreate) SetUpdatedAt(t time.Time) *VerificationTokenCreate {
	vtc.mutation.SetUpdatedAt(t)
	return vtc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (vtc *VerificationTokenCreate) SetNillableUpdatedAt(t *time.Time) *VerificationTokenCreate {
	if t != nil {
		vtc.SetUpdatedAt(*t)
	}
	return vtc
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (vtc *VerificationTokenCreate) AddUserIDs(ids ...int) *VerificationTokenCreate {
	vtc.mutation.AddUserIDs(ids...)
	return vtc
}

// AddUser adds the "user" edges to the User entity.
func (vtc *VerificationTokenCreate) AddUser(u ...*User) *VerificationTokenCreate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return vtc.AddUserIDs(ids...)
}

// Mutation returns the VerificationTokenMutation object of the builder.
func (vtc *VerificationTokenCreate) Mutation() *VerificationTokenMutation {
	return vtc.mutation
}

// Save creates the VerificationToken in the database.
func (vtc *VerificationTokenCreate) Save(ctx context.Context) (*VerificationToken, error) {
	vtc.defaults()
	return withHooks[*VerificationToken, VerificationTokenMutation](ctx, vtc.sqlSave, vtc.mutation, vtc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (vtc *VerificationTokenCreate) SaveX(ctx context.Context) *VerificationToken {
	v, err := vtc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (vtc *VerificationTokenCreate) Exec(ctx context.Context) error {
	_, err := vtc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vtc *VerificationTokenCreate) ExecX(ctx context.Context) {
	if err := vtc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (vtc *VerificationTokenCreate) defaults() {
	if _, ok := vtc.mutation.CreatedAt(); !ok {
		v := verificationtoken.DefaultCreatedAt()
		vtc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (vtc *VerificationTokenCreate) check() error {
	if _, ok := vtc.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "VerificationToken.token"`)}
	}
	if v, ok := vtc.mutation.Token(); ok {
		if err := verificationtoken.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "VerificationToken.token": %w`, err)}
		}
	}
	if _, ok := vtc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "VerificationToken.created_at"`)}
	}
	if len(vtc.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "VerificationToken.user"`)}
	}
	return nil
}

func (vtc *VerificationTokenCreate) sqlSave(ctx context.Context) (*VerificationToken, error) {
	if err := vtc.check(); err != nil {
		return nil, err
	}
	_node, _spec := vtc.createSpec()
	if err := sqlgraph.CreateNode(ctx, vtc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	vtc.mutation.id = &_node.ID
	vtc.mutation.done = true
	return _node, nil
}

func (vtc *VerificationTokenCreate) createSpec() (*VerificationToken, *sqlgraph.CreateSpec) {
	var (
		_node = &VerificationToken{config: vtc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: verificationtoken.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: verificationtoken.FieldID,
			},
		}
	)
	if value, ok := vtc.mutation.Token(); ok {
		_spec.SetField(verificationtoken.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := vtc.mutation.CreatedAt(); ok {
		_spec.SetField(verificationtoken.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := vtc.mutation.UpdatedAt(); ok {
		_spec.SetField(verificationtoken.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := vtc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   verificationtoken.UserTable,
			Columns: []string{verificationtoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// VerificationTokenCreateBulk is the builder for creating many VerificationToken entities in bulk.
type VerificationTokenCreateBulk struct {
	config
	builders []*VerificationTokenCreate
}

// Save creates the VerificationToken entities in the database.
func (vtcb *VerificationTokenCreateBulk) Save(ctx context.Context) ([]*VerificationToken, error) {
	specs := make([]*sqlgraph.CreateSpec, len(vtcb.builders))
	nodes := make([]*VerificationToken, len(vtcb.builders))
	mutators := make([]Mutator, len(vtcb.builders))
	for i := range vtcb.builders {
		func(i int, root context.Context) {
			builder := vtcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VerificationTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, vtcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, vtcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, vtcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (vtcb *VerificationTokenCreateBulk) SaveX(ctx context.Context) []*VerificationToken {
	v, err := vtcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (vtcb *VerificationTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := vtcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vtcb *VerificationTokenCreateBulk) ExecX(ctx context.Context) {
	if err := vtcb.Exec(ctx); err != nil {
		panic(err)
	}
}
