// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/renaldyhidayatt/redditgoent/ent/predicate"
	"github.com/renaldyhidayatt/redditgoent/ent/user"
	"github.com/renaldyhidayatt/redditgoent/ent/verificationtoken"
)

// VerificationTokenUpdate is the builder for updating VerificationToken entities.
type VerificationTokenUpdate struct {
	config
	hooks    []Hook
	mutation *VerificationTokenMutation
}

// Where appends a list predicates to the VerificationTokenUpdate builder.
func (vtu *VerificationTokenUpdate) Where(ps ...predicate.VerificationToken) *VerificationTokenUpdate {
	vtu.mutation.Where(ps...)
	return vtu
}

// SetToken sets the "token" field.
func (vtu *VerificationTokenUpdate) SetToken(s string) *VerificationTokenUpdate {
	vtu.mutation.SetToken(s)
	return vtu
}

// SetCreatedAt sets the "created_at" field.
func (vtu *VerificationTokenUpdate) SetCreatedAt(t time.Time) *VerificationTokenUpdate {
	vtu.mutation.SetCreatedAt(t)
	return vtu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (vtu *VerificationTokenUpdate) SetNillableCreatedAt(t *time.Time) *VerificationTokenUpdate {
	if t != nil {
		vtu.SetCreatedAt(*t)
	}
	return vtu
}

// SetUpdatedAt sets the "updated_at" field.
func (vtu *VerificationTokenUpdate) SetUpdatedAt(t time.Time) *VerificationTokenUpdate {
	vtu.mutation.SetUpdatedAt(t)
	return vtu
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (vtu *VerificationTokenUpdate) ClearUpdatedAt() *VerificationTokenUpdate {
	vtu.mutation.ClearUpdatedAt()
	return vtu
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (vtu *VerificationTokenUpdate) AddUserIDs(ids ...int) *VerificationTokenUpdate {
	vtu.mutation.AddUserIDs(ids...)
	return vtu
}

// AddUser adds the "user" edges to the User entity.
func (vtu *VerificationTokenUpdate) AddUser(u ...*User) *VerificationTokenUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return vtu.AddUserIDs(ids...)
}

// Mutation returns the VerificationTokenMutation object of the builder.
func (vtu *VerificationTokenUpdate) Mutation() *VerificationTokenMutation {
	return vtu.mutation
}

// ClearUser clears all "user" edges to the User entity.
func (vtu *VerificationTokenUpdate) ClearUser() *VerificationTokenUpdate {
	vtu.mutation.ClearUser()
	return vtu
}

// RemoveUserIDs removes the "user" edge to User entities by IDs.
func (vtu *VerificationTokenUpdate) RemoveUserIDs(ids ...int) *VerificationTokenUpdate {
	vtu.mutation.RemoveUserIDs(ids...)
	return vtu
}

// RemoveUser removes "user" edges to User entities.
func (vtu *VerificationTokenUpdate) RemoveUser(u ...*User) *VerificationTokenUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return vtu.RemoveUserIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (vtu *VerificationTokenUpdate) Save(ctx context.Context) (int, error) {
	vtu.defaults()
	return withHooks[int, VerificationTokenMutation](ctx, vtu.sqlSave, vtu.mutation, vtu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (vtu *VerificationTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := vtu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (vtu *VerificationTokenUpdate) Exec(ctx context.Context) error {
	_, err := vtu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vtu *VerificationTokenUpdate) ExecX(ctx context.Context) {
	if err := vtu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (vtu *VerificationTokenUpdate) defaults() {
	if _, ok := vtu.mutation.UpdatedAt(); !ok && !vtu.mutation.UpdatedAtCleared() {
		v := verificationtoken.UpdateDefaultUpdatedAt()
		vtu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (vtu *VerificationTokenUpdate) check() error {
	if v, ok := vtu.mutation.Token(); ok {
		if err := verificationtoken.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "VerificationToken.token": %w`, err)}
		}
	}
	return nil
}

func (vtu *VerificationTokenUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := vtu.check(); err != nil {
		return n, err
	}
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   verificationtoken.Table,
			Columns: verificationtoken.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: verificationtoken.FieldID,
			},
		},
	}
	if ps := vtu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := vtu.mutation.Token(); ok {
		_spec.SetField(verificationtoken.FieldToken, field.TypeString, value)
	}
	if value, ok := vtu.mutation.CreatedAt(); ok {
		_spec.SetField(verificationtoken.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := vtu.mutation.UpdatedAt(); ok {
		_spec.SetField(verificationtoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if vtu.mutation.UpdatedAtCleared() {
		_spec.ClearField(verificationtoken.FieldUpdatedAt, field.TypeTime)
	}
	if vtu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   verificationtoken.UserTable,
			Columns: []string{verificationtoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vtu.mutation.RemovedUserIDs(); len(nodes) > 0 && !vtu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   verificationtoken.UserTable,
			Columns: []string{verificationtoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vtu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   verificationtoken.UserTable,
			Columns: []string{verificationtoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, vtu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{verificationtoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	vtu.mutation.done = true
	return n, nil
}

// VerificationTokenUpdateOne is the builder for updating a single VerificationToken entity.
type VerificationTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VerificationTokenMutation
}

// SetToken sets the "token" field.
func (vtuo *VerificationTokenUpdateOne) SetToken(s string) *VerificationTokenUpdateOne {
	vtuo.mutation.SetToken(s)
	return vtuo
}

// SetCreatedAt sets the "created_at" field.
func (vtuo *VerificationTokenUpdateOne) SetCreatedAt(t time.Time) *VerificationTokenUpdateOne {
	vtuo.mutation.SetCreatedAt(t)
	return vtuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (vtuo *VerificationTokenUpdateOne) SetNillableCreatedAt(t *time.Time) *VerificationTokenUpdateOne {
	if t != nil {
		vtuo.SetCreatedAt(*t)
	}
	return vtuo
}

// SetUpdatedAt sets the "updated_at" field.
func (vtuo *VerificationTokenUpdateOne) SetUpdatedAt(t time.Time) *VerificationTokenUpdateOne {
	vtuo.mutation.SetUpdatedAt(t)
	return vtuo
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (vtuo *VerificationTokenUpdateOne) ClearUpdatedAt() *VerificationTokenUpdateOne {
	vtuo.mutation.ClearUpdatedAt()
	return vtuo
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (vtuo *VerificationTokenUpdateOne) AddUserIDs(ids ...int) *VerificationTokenUpdateOne {
	vtuo.mutation.AddUserIDs(ids...)
	return vtuo
}

// AddUser adds the "user" edges to the User entity.
func (vtuo *VerificationTokenUpdateOne) AddUser(u ...*User) *VerificationTokenUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return vtuo.AddUserIDs(ids...)
}

// Mutation returns the VerificationTokenMutation object of the builder.
func (vtuo *VerificationTokenUpdateOne) Mutation() *VerificationTokenMutation {
	return vtuo.mutation
}

// ClearUser clears all "user" edges to the User entity.
func (vtuo *VerificationTokenUpdateOne) ClearUser() *VerificationTokenUpdateOne {
	vtuo.mutation.ClearUser()
	return vtuo
}

// RemoveUserIDs removes the "user" edge to User entities by IDs.
func (vtuo *VerificationTokenUpdateOne) RemoveUserIDs(ids ...int) *VerificationTokenUpdateOne {
	vtuo.mutation.RemoveUserIDs(ids...)
	return vtuo
}

// RemoveUser removes "user" edges to User entities.
func (vtuo *VerificationTokenUpdateOne) RemoveUser(u ...*User) *VerificationTokenUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return vtuo.RemoveUserIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (vtuo *VerificationTokenUpdateOne) Select(field string, fields ...string) *VerificationTokenUpdateOne {
	vtuo.fields = append([]string{field}, fields...)
	return vtuo
}

// Save executes the query and returns the updated VerificationToken entity.
func (vtuo *VerificationTokenUpdateOne) Save(ctx context.Context) (*VerificationToken, error) {
	vtuo.defaults()
	return withHooks[*VerificationToken, VerificationTokenMutation](ctx, vtuo.sqlSave, vtuo.mutation, vtuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (vtuo *VerificationTokenUpdateOne) SaveX(ctx context.Context) *VerificationToken {
	node, err := vtuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (vtuo *VerificationTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := vtuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vtuo *VerificationTokenUpdateOne) ExecX(ctx context.Context) {
	if err := vtuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (vtuo *VerificationTokenUpdateOne) defaults() {
	if _, ok := vtuo.mutation.UpdatedAt(); !ok && !vtuo.mutation.UpdatedAtCleared() {
		v := verificationtoken.UpdateDefaultUpdatedAt()
		vtuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (vtuo *VerificationTokenUpdateOne) check() error {
	if v, ok := vtuo.mutation.Token(); ok {
		if err := verificationtoken.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "VerificationToken.token": %w`, err)}
		}
	}
	return nil
}

func (vtuo *VerificationTokenUpdateOne) sqlSave(ctx context.Context) (_node *VerificationToken, err error) {
	if err := vtuo.check(); err != nil {
		return _node, err
	}
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   verificationtoken.Table,
			Columns: verificationtoken.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: verificationtoken.FieldID,
			},
		},
	}
	id, ok := vtuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VerificationToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := vtuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, verificationtoken.FieldID)
		for _, f := range fields {
			if !verificationtoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != verificationtoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := vtuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := vtuo.mutation.Token(); ok {
		_spec.SetField(verificationtoken.FieldToken, field.TypeString, value)
	}
	if value, ok := vtuo.mutation.CreatedAt(); ok {
		_spec.SetField(verificationtoken.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := vtuo.mutation.UpdatedAt(); ok {
		_spec.SetField(verificationtoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if vtuo.mutation.UpdatedAtCleared() {
		_spec.ClearField(verificationtoken.FieldUpdatedAt, field.TypeTime)
	}
	if vtuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   verificationtoken.UserTable,
			Columns: []string{verificationtoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vtuo.mutation.RemovedUserIDs(); len(nodes) > 0 && !vtuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   verificationtoken.UserTable,
			Columns: []string{verificationtoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vtuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   verificationtoken.UserTable,
			Columns: []string{verificationtoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &VerificationToken{config: vtuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, vtuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{verificationtoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	vtuo.mutation.done = true
	return _node, nil
}
