// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/renaldyhidayatt/redditgoent/ent/verificationtoken"
)

// VerificationToken is the model entity for the VerificationToken schema.
type VerificationToken struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Token holds the value of the "token" field.
	Token string `json:"token,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the VerificationTokenQuery when eager-loading is set.
	Edges VerificationTokenEdges `json:"edges"`
}

// VerificationTokenEdges holds the relations/edges for other nodes in the graph.
type VerificationTokenEdges struct {
	// User holds the value of the user edge.
	User []*User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading.
func (e VerificationTokenEdges) UserOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*VerificationToken) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case verificationtoken.FieldID:
			values[i] = new(sql.NullInt64)
		case verificationtoken.FieldToken:
			values[i] = new(sql.NullString)
		case verificationtoken.FieldCreatedAt, verificationtoken.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type VerificationToken", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the VerificationToken fields.
func (vt *VerificationToken) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case verificationtoken.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			vt.ID = int(value.Int64)
		case verificationtoken.FieldToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token", values[i])
			} else if value.Valid {
				vt.Token = value.String
			}
		case verificationtoken.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				vt.CreatedAt = value.Time
			}
		case verificationtoken.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				vt.UpdatedAt = value.Time
			}
		}
	}
	return nil
}

// QueryUser queries the "user" edge of the VerificationToken entity.
func (vt *VerificationToken) QueryUser() *UserQuery {
	return NewVerificationTokenClient(vt.config).QueryUser(vt)
}

// Update returns a builder for updating this VerificationToken.
// Note that you need to call VerificationToken.Unwrap() before calling this method if this VerificationToken
// was returned from a transaction, and the transaction was committed or rolled back.
func (vt *VerificationToken) Update() *VerificationTokenUpdateOne {
	return NewVerificationTokenClient(vt.config).UpdateOne(vt)
}

// Unwrap unwraps the VerificationToken entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (vt *VerificationToken) Unwrap() *VerificationToken {
	_tx, ok := vt.config.driver.(*txDriver)
	if !ok {
		panic("ent: VerificationToken is not a transactional entity")
	}
	vt.config.driver = _tx.drv
	return vt
}

// String implements the fmt.Stringer.
func (vt *VerificationToken) String() string {
	var builder strings.Builder
	builder.WriteString("VerificationToken(")
	builder.WriteString(fmt.Sprintf("id=%v, ", vt.ID))
	builder.WriteString("token=")
	builder.WriteString(vt.Token)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(vt.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(vt.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// VerificationTokens is a parsable slice of VerificationToken.
type VerificationTokens []*VerificationToken

func (vt VerificationTokens) config(cfg config) {
	for _i := range vt {
		vt[_i].config = cfg
	}
}
