// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// Subreddit is the predicate function for subreddit builders.
type Subreddit func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// VerificationToken is the predicate function for verificationtoken builders.
type VerificationToken func(*sql.Selector)

// Vote is the predicate function for vote builders.
type Vote func(*sql.Selector)
